config/routes.rb
Rails.application.routes.draw do

  get 'backoffice', to: 'backoffice/dashboard#index'

  namespace :backoffice do
    resources :categories, except: [:show, :destroy]
    resources :admins, except: [:show]
    root 'dashboard#index', to: 'dashboard'
    #root 'dashboard#index', as: :authenticated_root
  end

  namespace :site do
    get  'home', to: 'home#index'
  end


  devise_for :members
  devise_for :admins

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "site/home#index"
  
  #get '/', to: redirect('site/home')


end

app/models/admin.rb
class Admin < ApplicationRecord
  rolify
  #Todo usuario cadastrado no sistema role de Administrador
  after_create :assing_default_role
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  #validação
  validates_presence_of :name


  def assing_default_role
    self.add_role(:NewUser) if self.roles.blank?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	#Verifica se estar em branco descrição
	validates_presence_of :description
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :admins, :join_table => :admins_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	#Paramentro Permissão do Devise
	before_action :configure_permitted_parameters, if: :devise_controller?
	#Escolher Layouts pelo Devise
	layout :layout_by_resource

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :password, :name])
	end

	def layout_by_resource
		if devise_controller? && resource_name == :admin
			"backoffice_devise"
		else
			"application"
		end
	end
end

app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController
  before_action :set_admin, only: [:edit, :update, :destroy]

  def index
    #@admins = Admin.order("admins.id asc")
    @search = Admin.joins(:roles)

    if current_admin.has_role? :SuperAdmin    
      @admins = @search.order("admins.id asc")
    elsif current_admin.has_role? :Admin
      @admins = @search.where("roles.name=? or roles.name=?", 'Admin', 'NewUser').order("admins.name asc")
    else
      @admins = @search.where("admins.id=?", current_admin.id).order("admins.name asc")
    end
  end

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(params_admin)
    if @admin.save
      redirect_to backoffice_admins_path 
      flash[:success] =  "O Usuario #{@admin.email} foi criado com Sucesso."
    else
      render :new
      flash[:alert] = "O Usuario não foi cadastrado!"
    end
  end

  def edit
  end

  def update
    params[:admin].delete(:password) if params[:admin][:password].blank?
    params[:admin].delete(:password_confirmation) if params[:admin][:password].blank? 
    if @admin.update(params_admin)
      redirect_to backoffice_admins_path
      flash[:success] = "O Usuario #{@admin.email} foi atualizado com Sucesso."
    else
      render :edit
      flash[:alert] = "O Usuario não foi atualizado!"
    end
  end

  def destroy
    admin_email = @admin.email
    if @admin.destroy
      redirect_to backoffice_admins_path
      flash[:success] = "O Usuario #{admin_email} foi excluido com Sucesso."
    else
      render :index
      flash[:alert] = "O Usuario não foi excluido!"
    end

  end
  
  private

  def set_admin
    @admin = Admin.find(params[:id])
  end

  def params_admin
    params.require(:admin).permit(:name, :email, :password, :password_confirmation, role_ids: [])
  end
end

app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < BackofficeController
  before_action :set_category, only: [:edit, :update]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params_category)
    if @category.save
      redirect_to backoffice_categories_path 
      flash[:success] =  "A categoria #{@category.description} foi criado com Sucesso."
    else
      render :new
      flash[:alert] = "A categoria não foi cadastrado!"
    end
  end

  def edit
  end

  def update
    if @category.update(params_category)
      redirect_to backoffice_categories_path
      flash[:success] = "A categoria #{@category.description} foi atualizado com Sucesso."
    else
      render :edit
      flash[:alert] = "A categoria não foi atualizado!"
    end
  end
  
  private

  def set_category
    @category = Category.find(params[:id])
  end

  def params_category
    params.require(:category).permit(:description)
  end
end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < BackofficeController
  def index
  end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
	before_action :authenticate_admin!
	layout "backoffice"
end

app/controllers/site/home_controller.rb
class Site::HomeController < ApplicationController
  layout "site"
  def index
    @categories = Category.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
end

app/helpers/backoffice/categories_helper.rb
module Backoffice::CategoriesHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/helpers/site/home_helper.rb
module Site::HomeHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%#- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%#= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<%# end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/backoffice/admins/edit.html.erb
<%= render partial: "backoffice/admins/shared/form", locals: {action: "Editando Administrador"}%>

app/views/backoffice/admins/index.html.erb
<div class="page-heading">
	<h1 class="page-title">Administrador</h1>
</div>
<div class="page-content fade-in-up">
	<div class="ibox">
		<div class="ibox-head">
			<div class="ibox-title">Listando Administradores</div>
			<%= link_to new_backoffice_admin_path, class: "btn btn-success btn-circle" do%>
			<i class="fa fa-plus"></i>
			<% end -%>
		</div>
		<div class="ibox-body">
			<table class="table table-hover">
				<thead>
					<tr>
						<th>#</th>
						<th>Nome</th>
						<th>Email</th>
						<th>Role</th>
						<th>Opção</th>
					</tr>
				</thead>
				<tbody>
					<% @admins.each do |admin| %>
					<%#= admin.roles.inspect %>
					<tr>
						<td><%= admin.id%></td>
						<td><%= admin.name%></td>
						<td><%= admin.email%></td>
						<td><%= admin.roles.first.name rescue '---'%></td>
						<td style=" width: 150px;">
							<%= link_to edit_backoffice_admin_path(admin), class: "btn btn-default btn-xs" do%>
							<i class="fa fa-pencil font-14"></i></button>
							<% end -%>
							<% if current_admin.has_role? :SuperAdmin %>
							<% if current_admin.id != admin.id %>
							<%= link_to backoffice_admin_path(admin), method: :delete, class: "btn btn-default btn-xs", data: {confirm: "Você deseja excluir <b>#{admin.email}</b> ?"} do %>
							<i class="fa fa-trash font-14"></i>
							<% end -%>
	
							<% end -%>
							<% end -%>
						</td>
					</tr>
					<% end -%>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/backoffice/admins/new.html.erb
<%= render partial: "backoffice/admins/shared/form", locals: {action: "Criando Administrador"}%>

app/views/backoffice/admins/shared/_form.html.erb
<div class="page-heading">
    <h1 class="page-title">Administrador</h1>
</div>

<% if @admin.errors.any? %>
<div class="alert alert-danger alert-dismissable fade show">
    <button class="close" data-dismiss="alert" aria-label="Close">×</button>
    <% @admin.errors.full_messages.each do |message|  %>
    <%= message %><br>
    <% end -%>

</div>
<% end -%>


<div class="page-content fade-in-up">
    <div class="ibox">
        <div class="ibox-head">
            <div class="ibox-title"><%= action %></div>
        </div>
        <div class="ibox-body" style="">
            <%= form_for([:backoffice, @admin]) do |f| %>
            <div class="">
                <div class="form-group">
                    <label>Nome</label>
                    <%= f.text_field :name, class: "form-control", placeholder: "Nome" %>
                </div>
                <div class="form-group">
                    <label>Email</label>
                    <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
                </div>

                <div class="form-group">
                    <label>Role</label>
                    <%#= f.collection_check_boxes :role_ids, Role.all, :id, :name,
                        {:item_wrapper_class => 'ui-checkbox'} %>
                        <%= f.select :role_ids, options_for_select(Role.all.map{|role| [role.name, role.id]}, @admin.role_ids), {},  {:multiple => true, inlcude_blank: false, class: "form-control input-sm selectpicker"} %>

                        <%= f.collection_radio_buttons :role_ids, Role.all, :id, :name, include_hidden: false %>
                    </div>

                    <div class="form-group">
                        <label>Senha</label>
                        <%= f.password_field :password, class: "form-control", placeholder: "Senha" %>
                    </div>
                    <div class="form-group">
                        <label>Confirmação da Senha</label>
                        <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirmação da Senha" %>
                    </div>
                    <button type="submit" class="btn btn-default">Salvar</button>
                    <% end -%>
                </div>
            </div>
        </div>
    </div>

app/views/backoffice/categories/edit.html.erb
<%= render partial: "backoffice/categories/shared/form", locals: {action: "Editando Categoria"}%>

app/views/backoffice/categories/index.html.erb
<div class="page-heading">
  <h1 class="page-title">Categorias</h1>
</div>
<div class="page-content fade-in-up">
  <div class="ibox">
    <div class="ibox-head">
      <div class="ibox-title">Listando Categorias</div>
      <%= link_to new_backoffice_category_path, class: "btn btn-success btn-circle" do%>
      <i class="fa fa-plus"></i>
      <% end -%>
    </div>
    <div class="ibox-body">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>#</th>
            <th>Descrição</th>
            <th>Opção</th>
          </tr>
        </thead>
        <tbody>
          <% @categories.each do |category| %>
          <tr>
            <td><%= category.id%></td>
            <td><%= category.description%></td>
            <td style=" width: 150px;">
              <%= link_to edit_backoffice_category_path(category), class: "btn btn-default btn-xs" do%>
              <i class="fa fa-pencil font-14"></i></button>
              <% end -%>
              <button class="btn btn-default btn-xs" data-toggle="tooltip" data-original-title="Delete"><i class="fa fa-trash font-14"></i></button>
            </td>
          </tr>
          <% end -%>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/backoffice/categories/new.html.erb
<%= render partial: "backoffice/categories/shared/form", locals: {action: "Criando Categoria"}%>

app/views/backoffice/dashboard/index.html.erb
<div class="page-heading">
	<h1 class="page-title">Dashboard</h1>
</div>
<div class="page-content fade-in-up">

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Escamboapp20</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/backoffice.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>BackOffice - EscamboApp</title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'backoffice', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'backoffice', 'data-turbolinks-track': 'reload' %>

</head>

<body class="fixed-navbar">

  <% flash.each do |key, value| %>
    <% if !value.blank? and !value.nil? %>
      <div class="alert alert-<%= key=='notice' ? 'success' : key=='alert' ? 'danger' : key %> alert-dismissable pull-rigth alert-position alert-time">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <%= value %>
      </div>
    <% end %>
  <% end %>

  <div class="page-wrapper">
    <header class="header">
      <%= render "layouts/backoffice_shared/nav" %>
    </header>
    <nav class="page-sidebar" id="sidebar">
      <%= render "layouts/backoffice_shared/sidebar" %>
    </nav>

    <div class="content-wrapper">
      <%= yield %>

      <footer class="page-footer">
        <div class="font-13">2018 © <b>AdminCAST</b> - All rights reserved.</div>
        <a class="px-4" href="http://themeforest.net/item/adminca-responsive-bootstrap-4-3-angular-4-admin-dashboard-template/20912589" target="_blank">BUY PREMIUM</a>
        <div class="to-top"><i class="fa fa-angle-double-up"></i></div>
      </footer>
    </div>
  </div>

</body>

</html>

app/views/layouts/backoffice_devise.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>BackOffice - EscamboApp</title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'backoffice-login', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'backoffice', 'data-turbolinks-track': 'reload' %>

</head>

<body class="bg-silver-300 has-animation">
  <% flash.each do |key, value| %>
    <% if !value.blank? and !value.nil? %>
      <div class="alert alert-<%= key=='notice' ? 'success' : key=='alert' ? 'danger' : key %> alert-dismissable alert-time">
        <%= value %>
      </div>
    <% end %>
  <% end %>

      <%= yield %>


</body>

</html>

app/views/layouts/backoffice_shared/_nav.html.erb
  <div class="page-brand">
    <a class="link" href="/">
        <span class="brand">Admin
            <span class="brand-tip">CAST</span>
        </span>
        <span class="brand-mini">AC</span>
    </a>
</div>
<div class="flexbox flex-1">
    <!-- START TOP-LEFT TOOLBAR-->
    <ul class="nav navbar-toolbar">
        <li>
            <a class="nav-link sidebar-toggler js-sidebar-toggler">
                <i class="fa fa-bars"></i></a>
        </li>
        
    </ul>
    <!-- END TOP-LEFT TOOLBAR-->
    <!-- START TOP-RIGHT TOOLBAR-->
    <ul class="nav navbar-toolbar">

    <li class="dropdown dropdown-user">
        <a class="nav-link dropdown-toggle link" data-toggle="dropdown">
            <!-- <img src="./assets/img/admin-avatar.png" /> -->
            <span></span>Admin<i class="fa fa-angle-down m-l-5"></i></a>
            <ul class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item" href="profile.html"><i class="fa fa-user"></i>Profile</a>
                <a class="dropdown-item" href="profile.html"><i class="fa fa-cog"></i>Settings</a>
                <a class="dropdown-item" href="javascript:;"><i class="fa fa-support"></i>Support</a>
                <li class="dropdown-divider"></li>
                <%= link_to destroy_admin_session_path , class: "dropdown-item", method: :delete do %>
                <i class="fa fa-power-off"></i>
                Logout
                <% end %>
            </ul>
        </li>
    </ul>
    <!-- END TOP-RIGHT TOOLBAR-->
</div>

app/views/layouts/backoffice_shared/_sidebar.html.erb
<!-- START SIDEBAR-->
<div id="sidebar-collapse">
<div class="admin-block d-flex">
    <!-- <div>
        <img src="/assets/images/admin-avatar.png" width="45px" />
    </div> -->
    <div class="admin-info">
        <div class="font-strong"><%= current_admin.name %></div><small><%= current_admin.roles.first.name rescue '---' %></small></div>
    </div>
    <ul class="side-menu metismenu">
        <li class="<%= controller_name=="dashboard" ? 'active' : '' %>">
          <%= link_to backoffice_path do%>
          <i class="sidebar-item-icon fa fa-th-large"></i> 
          <span class="nav-label">Dashboard</span>
          <% end -%>
      </li>

      <li class="<%= controller_name=="admins" ? 'active' : '' %>">
        <a href="javascript:;"><i class="sidebar-item-icon fa fa-users"></i>
            <span class="nav-label">Administradores</span><i class="fa fa-angle-left arrow"></i></a>
            <ul class="nav-2-level collapse">
                <li><%= link_to "Listar", backoffice_admins_path%></li>
                <li><%= link_to "Inserir", new_backoffice_admin_path %></li>

            </ul>
        </li>
        <li class="<%= controller_name=="categories" ? 'active' : '' %>">
            <a href="javascript:;"><i class="sidebar-item-icon fa fa-th-list"></i>
                <span class="nav-label">Categorias</span><i class="fa fa-angle-left arrow"></i></a>
                <ul class="nav-2-level collapse">
                    <li><%= link_to "Listar", backoffice_categories_path%></li>
                    <li><%= link_to "Inserir", new_backoffice_category_path%></li>

                </ul>
            </li>


            <!-- <li class="heading">FEATURES</li>
            <li>
                <a href="javascript:;"><i class="sidebar-item-icon fa fa-bookmark"></i>
                    <span class="nav-label">Basic UI</span><i class="fa fa-angle-left arrow"></i></a>
                    <ul class="nav-2-level collapse">
                        <li>
                            <a href="colors.html">Colors</a>
                        </li>
                        <li>
                            <a href="typography.html">Typography</a>
                        </li>
                        <li>
                            <a href="panels.html">Panels</a>
                        </li>
                        <li>
                            <a href="buttons.html">Buttons</a>
                        </li>
                        <li>
                            <a href="tabs.html">Tabs</a>
                        </li>
                        <li>
                            <a href="alerts_tooltips.html">Alerts &amp; Tooltips</a>
                        </li>
                        <li>
                            <a href="badges_progress.html">Badges &amp; Progress</a>
                        </li>
                        <li>
                            <a href="lists.html">List</a>
                        </li>
                        <li>
                            <a href="cards.html">Card</a>
                        </li>
                    </ul>
                </li> -->

                </ul>
            </li>
        </ul>
    </li>
</ul>
</div>
<!-- END SIDEBAR-->

app/views/layouts/site.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>EscamboApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'site', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'site', 'data-turbolinks-track': 'reload' %>

</head>

<body>
    <%= render "layouts/site_shared/nav" %>
    <%= yield %>
    <%= render "layouts/site_shared/footer" %>
</body>

</html>

app/views/layouts/site_shared/_footer.html.erb
<div class="container">

	<hr>

	<!-- Footer -->
	<footer>
		<div class="row">
			<div class="col-lg-12">
				<p>Copyright &copy; Your Website 2014</p>
			</div>
		</div>
	</footer>

</div>

app/views/layouts/site_shared/_nav.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	<div class="container">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">EscamboApp</a>
		</div>
		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li>
					<a href="#">About</a>
				</li>
				<li>
					<a href="#">Services</a>
				</li>
				<li>
					<a href="#">Contact</a>
				</li>
				
			</ul>
			<ul class="nav navbar-nav pull-right">
				<li>
					<% if admin_signed_in? %>
					<%= link_to "dashboard", backoffice_path, class: "" %> 
					<% else %>
					<a href="/backoffice">Log In</a>
					<% end -%>
				</li>

			</ul>

		</div>
		<!-- /.navbar-collapse -->
	</div>
	<!-- /.container -->
</nav>

app/views/members/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/members/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>